src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $initial_fee = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $additional_fee = null;

    #[ORM\Column]
    private ?int $attempt_limit = null;

    #[ORM\ManyToOne(inversedBy: 'categories')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Tournament $tournament = null;

    #[ORM\ManyToOne(inversedBy: 'categories')]
    #[ORM\JoinColumn(nullable: false)]
    private ?CategoryGroup $category_group = null;

    /**
     * @var Collection<int, Attempt>
     */
    #[ORM\OneToMany(targetEntity: Attempt::class, mappedBy: 'category', orphanRemoval: true)]
    private Collection $attempts;

    public function __construct()
    {
        $this->attempts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getInitialFee(): ?string
    {
        return $this->initial_fee;
    }

    public function setInitialFee(string $initial_fee): static
    {
        $this->initial_fee = $initial_fee;

        return $this;
    }

    public function getAdditionalFee(): ?string
    {
        return $this->additional_fee;
    }

    public function setAdditionalFee(string $additional_fee): static
    {
        $this->additional_fee = $additional_fee;

        return $this;
    }

    public function getAttemptLimit(): ?int
    {
        return $this->attempt_limit;
    }

    public function setAttemptLimit(int $attempt_limit): static
    {
        $this->attempt_limit = $attempt_limit;

        return $this;
    }

    public function getTournament(): ?Tournament
    {
        return $this->tournament;
    }

    public function setTournament(?Tournament $tournament): static
    {
        $this->tournament = $tournament;

        return $this;
    }

    public function getCategoryGroup(): ?CategoryGroup
    {
        return $this->category_group;
    }

    public function setCategoryGroup(?CategoryGroup $category_group): static
    {
        $this->category_group = $category_group;

        return $this;
    }

    /**
     * @return Collection<int, Attempt>
     */
    public function getAttempts(): Collection
    {
        return $this->attempts;
    }

    public function addAttempt(Attempt $attempt): static
    {
        if (!$this->attempts->contains($attempt)) {
            $this->attempts->add($attempt);
            $attempt->setCategory($this);
        }

        return $this;
    }

    public function removeAttempt(Attempt $attempt): static
    {
        if ($this->attempts->removeElement($attempt)) {
            // set the owning side to null (unless already changed)
            if ($attempt->getCategory() === $this) {
                $attempt->setCategory(null);
            }
        }

        return $this;
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Repository\CategoryRepository;
use App\Repository\CategoryGroupRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;

#[Route('/category')]
final class CategoryController extends AbstractController
{
    #[Route(name: '/', methods: ['GET'])]
    public function index(CategoryRepository $categoryRepository): Response
    {
        return $this->render('category/index.html.twig', [
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_category_show', methods: ['GET'])]
    public function show(Category $category): Response
    {
        return $this->render('category/show.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/admin/{id}', name: 'app_category_delete', methods: ['POST'])]
    public function delete(Request $request, Category $category, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($category);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/admin/category_edit/{id}', name: 'app_category_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, int $id, CategoryRepository $categoryRepository, CategoryGroupRepository $categoryGroupRepository, EntityManagerInterface $entityManager): Response
    {
        $categories = $categoryRepository->getCategories($id);
        $categoryGroups = $categoryGroupRepository->getCategoryGroups($id);

        return $this->render('category/edit.html.twig', [
            'category' => $categories,
            'categoryGroups' => $categoryGroups,
        ]);
    }
}

templates/category/_delete_form.html.twig
<form method="post" action="{{ path('app_category_delete', {'id': category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
    <button class="btn">Delete</button>
</form>

templates/category/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/category/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ustawienia Kategorii{% endblock %}

{% block body %}
    <h1>Ustawienia Kategorii</h1>




{% endblock %}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Category index{% endblock %}

{% block body %}
    <h1>Category index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Initial_fee</th>
                <th>Additional_fee</th>
                <th>Attempt_limit</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for category in categories %}
            <tr>
                <td>{{ category.id }}</td>
                <td>{{ category.name }}</td>
                <td>{{ category.initialFee }}</td>
                <td>{{ category.additionalFee }}</td>
                <td>{{ category.attemptLimit }}</td>
                <td>
                    <a href="{{ path('app_category_show', {'id': category.id}) }}">show</a>
                    <a href="{{ path('app_category_edit', {'id': category.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_category_new') }}">Create new</a>
{% endblock %}

templates/category/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Category{% endblock %}

{% block body %}
    <h1>Create new Category</h1>

    {{ include('category/_form.html.twig') }}

    <a href="{{ path('app_category_index') }}">back to list</a>
{% endblock %}

templates/category/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Category{% endblock %}

{% block body %}
    <h1>Category</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ category.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ category.name }}</td>
            </tr>
            <tr>
                <th>Initial_fee</th>
                <td>{{ category.initialFee }}</td>
            </tr>
            <tr>
                <th>Additional_fee</th>
                <td>{{ category.additionalFee }}</td>
            </tr>
            <tr>
                <th>Attempt_limit</th>
                <td>{{ category.attemptLimit }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_category_index') }}">back to list</a>

    <a href="{{ path('app_category_edit', {'id': category.id}) }}">edit</a>

    {{ include('category/_delete_form.html.twig') }}
{% endblock %}