src/Entity/Competitor.php
<?php

namespace App\Entity;

use App\Repository\CompetitorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompetitorRepository::class)]
class Competitor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\ManyToOne(inversedBy: 'competitors')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Association $association = null;

    /**
     * @var Collection<int, Attempt>
     */
    #[ORM\OneToMany(targetEntity: Attempt::class, mappedBy: 'competitor')]
    private Collection $attempts;

    public function __construct()
    {
        $this->attempts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAssociation(): ?Association
    {
        return $this->association;
    }

    public function setAssociation(?Association $association): static
    {
        $this->association = $association;

        return $this;
    }

    /**
     * @return Collection<int, Attempt>
     */
    public function getAttempts(): Collection
    {
        return $this->attempts;
    }

    public function addAttempt(Attempt $attempt): static
    {
        if (!$this->attempts->contains($attempt)) {
            $this->attempts->add($attempt);
            $attempt->setCompetitor($this);
        }

        return $this;
    }

    public function removeAttempt(Attempt $attempt): static
    {
        if ($this->attempts->removeElement($attempt)) {
            // set the owning side to null (unless already changed)
            if ($attempt->getCompetitor() === $this) {
                $attempt->setCompetitor(null);
            }
        }

        return $this;
    }
}

src/Form/CompetitorType.php
<?php

namespace App\Form;

use App\Entity\Association;
use App\Entity\Competitor;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompetitorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('association', EntityType::class, [
                'class' => Association::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Competitor::class,
        ]);
    }
}

src/Controller/CompetitorController.php
<?php

namespace App\Controller;

use App\Entity\Association;
use App\Entity\Competitor;
use App\Form\CompetitorType;
use App\Repository\CompetitorRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Repository\AssociationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/competitor')]
final class CompetitorController extends AbstractController
{
    #[Route(name: '/', methods: ['GET'])]
    public function index(CompetitorRepository $competitorRepository): Response
    {
        return $this->render('competitor/index.html.twig', [
            'competitors' => $competitorRepository->findAll(),
        ]);
    }

    #[Route('/admin/new/{id}', name: 'app_competitor_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, CompetitorRepository $competitorRepository, int $id): Response
    {
        $competitor = new Competitor();
        $form = $this->createForm(CompetitorType::class, $competitor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($competitor);
            $entityManager->flush();

            $this->addFlash('success', 'Pomyślnie dodano nowego zawodnika: ' . $competitor->getFirstName() . ' ' . $competitor->getLastName());
            $this->addFlash('info', 'Numer Zawodnika: ' . $competitor->getId());

            return $this->redirectToRoute('scoreboard', ['id' => $id], Response::HTTP_SEE_OTHER);
        }
        
        $competitors = $competitorRepository->findAll();
        return $this->render('competitor/new.html.twig', [
            'competitors' => $competitors,
            'competitor' => $competitor,
            'form' => $form,
            'tournamentid' => $id
        ]);
    }

    #[Route('/{id}', name: 'app_competitor_show', methods: ['GET'])]
    public function show(Competitor $competitor): Response
    {
        return $this->render('competitor/show.html.twig', [
            'competitor' => $competitor,
        ]);
    }

    #[Route('/admin/{id}/edit', name: 'app_competitor_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Competitor $competitor, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CompetitorType::class, $competitor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_competitor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('competitor/edit.html.twig', [
            'competitor' => $competitor,
            'form' => $form,
        ]);
    }

    #[Route('/admin/{id}/delete', name: 'app_competitor_delete', methods: ['POST'])]
    public function delete(Request $request, Competitor $competitor, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$competitor->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($competitor);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_competitor_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/admin/update', name: 'competitor_update', methods: ['POST'])]
    public function update(Request $request, CompetitorRepository $competitorRepository, AssociationRepository $associationRepository): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        if(!isset($data['id'])){
            return new JsonResponse(['success' => false, 'error' => 'Brak ID zawodnika']);
        }

        $competitor = $competitorRepository->find($data['id']);
        if(!$competitor){
            return new JsonResponse(['success' => false, 'error' => 'Zawodnik nie znaleziony']);
        }

        $competitor->setFirstName($data['first_name']);
        $competitor->setLastName($data['last_name']);
        $competitor->setAssociation($associationRepository->find($data['association_id']));

        $competitorRepository->getEntityManager()->flush();

        return new JsonResponse(['success' => true]);
    }


    #[Route('/admin/add', name: 'competitor_add', methods: ['POST'])]
    public function insert(Request $request, CompetitorRepository $competitorRepository, AssociationRepository $associationRepository): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        if(empty($data['first_name']) || empty($data['last_name']) || empty($data['association_id'])){
            return new JsonResponse(['success' => false, 'error' => 'Brak wymaganych danych']);
        }

        $association = $associationRepository->find($data['association_id']);
        if(!$association){
            return new JsonResponse(['success' => false, 'error' => 'Nieprawidłowe ID klubu']);
        }

        $competitor = new Competitor();
        $competitor->setFirstName($data['first_name']);
        $competitor->setLastName($data['last_name']);
        $competitor->setAssociation($association);

        $em = $competitorRepository->getEntityManager();
        $em->persist($competitor);
        $em->flush();

        return new JsonResponse([
            'success' => true,
            'competitor' => [
                'id' => $competitor->getId(),
                'first_name' => $competitor->getFirstName(),
                'last_name' => $competitor->getLastName(),
                'association_id' => $association->getId(),
                'association_name' => $association->getName()
            ]
        ]);
    }










}

templates/competitor/_delete_form.html.twig
<form method="post" action="{{ path('app_competitor_delete', {'id': competitor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ competitor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/competitor/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="confirm-button">Dodaj Zawodnika</button>
{{ form_end(form) }}

templates/competitor/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Competitor{% endblock %}

{% block body %}
    <h1>Edit Competitor</h1>

    {{ include('competitor/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_competitor_index') }}">back to list</a>

    {{ include('competitor/_delete_form.html.twig') }}
{% endblock %}

templates/competitor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Competitor index{% endblock %}

{% block body %}
    <h1>Competitor index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for competitor in competitors %}
            <tr>
                <td>{{ competitor.id }}</td>
                <td>{{ competitor.firstName }}</td>
                <td>{{ competitor.lastName }}</td>
                <td>
                    <a href="{{ path('app_competitor_show', {'id': competitor.id}) }}">show</a>
                    <a href="{{ path('app_competitor_edit', {'id': competitor.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_competitor_new') }}">Create new</a>
{% endblock %}

templates/competitor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nowy Zawodnik{% endblock %}

{% block body %}
<div class="flex-wrapper">
    <div class="basic-form">
        <h1>Dodaj Zawodnika</h1>

        {{ form_start(form) }}

            <div class="form-group">
                {{ form_label(form.first_name, 'Imię: ', {'label_attr': {'class': 'field-title'}}) }}
                {{ form_widget(form.first_name, {'attr': {'class': 'input-text-field'}}) }}
                {{ form_errors(form.first_name) }}
            </div>

            <div class="form-group">
                {{ form_label(form.last_name, 'Nazwisko: ', {'label_attr': {'class': 'field-title'}}) }}
                {{ form_widget(form.last_name, {'attr': {'class': 'input-text-field'}}) }}
                {{ form_errors(form.last_name) }}
            </div>

            <div class="form-group">
                {{ form_label(form.association, 'Stowarzyszenie: ', {'label_attr': {'class': 'field-title'}}) }}
                {{ form_widget(form.association, {'attr': {'class': 'expandable-list-label'}}) }}
                {{ form_errors(form.association) }}
            </div>

            <button class="confirm-button">Dodaj zawodnika</button>
            <a href="#" class="return-button" onclick="event.preventDefault(); if (window.history.length > 1) { history.back(); } else { window.location = '{{ path('scoreboard', {'id': tournamentid}) }}'; }">Powrót</a>

        {{ form_end(form) }}

    </div>
</div>

<div class="flex-wrapper">
    <div class="basic-form">
        <p id="compare" style="display:none;"></p>
        <h1>Istniejący Zawodnicy</h1>
        <ul id="competitor-list" class="expandable-list" style="position: static; display: block; max-height: none; border: none; border-radius: 0;">
            {% for competitor in competitors %}
                {% set competitor_string = competitor.first_name ~ ' ' ~ competitor.last_name ~ ' (' ~ competitor.association_name ~ ')' %}
                <li data-value="{{ competitor_string }}">{{ competitor_string }}</li>
            {% endfor %}
        </ul>
    </div>
</div>

{% set firstId = form.first_name.vars.id %}
{% set lastId = form.last_name.vars.id %}

<script>
    firstNameInput = document.getElementById('{{ firstId }}');
    lastNameInput = document.getElementById('{{ lastId }}');
    compareOutput = document.getElementById('compare');
    competitorList = document.getElementById('competitor-list');
    competitorItems = Array.from(competitorList.querySelectorAll('li'));

    function updateCompare() {
        const firstName = firstNameInput.value.trim();
        const lastName = lastNameInput.value.trim();
        const compareText = firstName + (firstName && lastName ? ' ' : '') + lastName;
        compareOutput.textContent = compareText;

        // Filtracja listy
        competitorItems.forEach(item => {
            const text = item.dataset.value.toLowerCase();
            if (text.includes(compareText.toLowerCase())) {
                item.style.display = '';
            } else {
                item.style.display = 'none';
            }
        });
    }

    firstNameInput.addEventListener('input', updateCompare);
    lastNameInput.addEventListener('input', updateCompare);

    updateCompare();
</script>

{% endblock %}

templates/competitor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Competitor{% endblock %}

{% block body %}
    <h1>Competitor</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ competitor.id }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ competitor.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ competitor.lastName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_competitor_index') }}">back to list</a>

    <a href="{{ path('app_competitor_edit', {'id': competitor.id}) }}">edit</a>

    {{ include('competitor/_delete_form.html.twig') }}
{% endblock %}